version: '3'
services:
  mongo:
    image: 'mongo:5.0'
    container_name: 'mongo-card'
    restart: 'no'
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata:
    driver: local